### ISSUE TITLE
Add comprehensive engines support

### ISSUE THREAD

**Issue by jmalcic** [hotwired/stimulus-rails#47]
There are a number of outstanding issues when using this gem with engines. I think it would be helpful to try to collect all the issues so that it's clear what needs fixing, and what's being fixed, and what already works.

- [ ] the `importmap_list_from` helper assumes relative paths are relative to `Rails.root`, as opposed to the root of an engine (#39 partially fixes this by allowing absolute paths, but it shouldn't be necessary to use absolute paths in the first place). #50 attempts to fix this by introducing new Sprockets directives.
- [x] import maps cannot be in a namespaced path: the import map is currently expected to always be in `app/javascripts/importmap.json`. Because of this, if multiple engines or an engine and an app provide an import map, one will overwrite the other(s). #41 allows import maps to be included from custom locations
- [ ] import maps cannot be composed: it currently [isn't possible to have multiple import maps on the same page](https://github.com/WICG/import-maps#installation). It isn't inconceivable that because of this (potentially multiple) engines and the mounting app would want to use make use of the same import map. Not really sure how common this situation is (it depends how you use engines). #50 fixes this by allowing importmaps to be merged by Sprockets.
- [ ] the install task doesn't work in engines: the install task currently uses tasks and references paths which only apply to main apps, not engines. #17 attempts to fix this ~(though needs conflicts resolving)~

**Comment by dhh** [comment]
Please do proceed to fix these 👍

**Comment by dhh** [comment]
This is no longer relevant as all the importmap stuff has been extracted to a separate gem.
